# Generated by Django 5.1.1 on 2024-12-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examset',
            name='exam_card_count',
            field=models.IntegerField(default=0),
        ),
    ]
