# Generated by Django 5.1.3 on 2024-11-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0003_delete_studyset_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Study Set Name')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('color_hex', models.CharField(max_length=7, verbose_name='Color (Hex Code)')),
            ],
        ),
    ]
