# Generated by Django 5.1.2 on 2024-11-25 21:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_studyset_color_hex_alter_studyset_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyset',
            old_name='name',
            new_name='set_name',
        ),
        migrations.RenameField(
            model_name='studyset',
            old_name='subject',
            new_name='set_subject',
        ),
        migrations.AddField(
            model_name='studyset',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
