# Generated by Django 5.1.3 on 2024-12-04 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_name_studyset_set_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyset',
            options={'verbose_name': 'Study Set'},
        ),
    ]
