# Generated by Django 5.1.3 on 2024-12-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_studyset_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyset',
            name='flashcard_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
