# Generated by Django 5.1.2 on 2024-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='set',
            new_name='flashcard_set',
        ),
        migrations.AlterField(
            model_name='flashcardset',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
