# Generated by Django 5.1.1 on 2024-12-09 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200)),
                ('definition', models.TextField()),
                ('isGotIt', models.BooleanField(default=False)),
                ('isNotSure', models.BooleanField(default=False)),
                ('study_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='dashboard.studyset')),
            ],
        ),
    ]
