# Generated by Django 5.1.2 on 2024-11-25 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_studyset_color_hex_alter_studyset_name_and_more'),
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='flashcard_set',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='study_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='dashboard.studyset'),
        ),
        migrations.DeleteModel(
            name='FlashcardSet',
        ),
    ]
