# Generated by Django 5.1.3 on 2024-12-04 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_name_studyset_set_name_and_more'),
        ('flashcards', '0002_remove_flashcard_flashcard_set_flashcard_study_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='study_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='dashboard.studyset'),
        ),
    ]
