# Generated by Django 5.1.3 on 2024-12-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0003_alter_flashcard_study_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='isGotIt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='isNotSure',
            field=models.BooleanField(default=False),
        ),
    ]
