# Generated by Django 5.1.3 on 2024-12-09 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0004_flashcard_isgotit_flashcard_isnotsure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='isGotIt',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='isNotSure',
        ),
    ]
