# Generated by Django 5.1.1 on 2024-12-09 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('exam_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_cards', to='dashboard.examset')),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
