# Generated by Django 5.1.1 on 2024-12-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examcard_delete_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examcard',
            old_name='answer',
            new_name='definition',
        ),
        migrations.RemoveField(
            model_name='examcard',
            name='question',
        ),
        migrations.AddField(
            model_name='examcard',
            name='term',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
